spring:
  application:
    name: TICKET-MANAGEMENT

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true