spring:
  application:
    name: USER_SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userpagenation
    username: root
    password: tiger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"